travis:
  secure:
    BINSTAR_TOKEN: Dx9SMc6ErSyoZc3WvqiPdw4l/JQyxSHzo9ej1AQc/XgUHkCNrRM4yYd+vQwAEVP/FDFK54/zMMeYQQA3L47jhxdIOEJjc3iaL3W/4U/SQRX94OTHZaqOBsp9kjSwrqUgcoEEoKf/3wM+TuVz8KxC+5d3YLFUPDUy9SwHyfdncMyDw2YLiQrV49eIz4pi6D9rArZ5zxy8/7SvAIgrUWj1PGZnu7mKcuQg2zFdgZxvgXOOhZpjS0nU7RuAebhHJrh/Lsrm2K5w/NJnyFR336BJ6bYgzGVUssZen8QIzS1dv7SbfzVMLg7DMmzYy6RP6umaYlfQsILw1pYt/jFgPBQawbM+qXz2On2NyTr1wTF58RYcNSUjtZO7fE4S43PYczVUjubp/ewFuicODQ5+qE5hjL43H8HvLYA2Ul7x1on750MKHV2287OrMcngdgLVCTJXInA27ljx0iA3GnetGuRPJgG7tNkT3qSPEwWpeCOBOHKvZY2CzyMr2yA2ZHNUI1prSFq39SIzi26ip5B1scFBvCuQkq7T/3NE91U6G3GDAPheSXPXCpkNOIBQVlzuwqL5h9lIAv0PSamNriBOCrtG/2xYGXBSkQH0/OYEBBBRkXnHW38pZ8SA1YhnHIVuQm1pkBl8Ohs0EP0fwxN076P0kX0oc5eP11zJWfavU9t8wbg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
